- govuk_navigation_helpers.gemspec
We need this gem to publish the gem to rubygems.org.
> Fix gem publishing

- Rakefile
This uses our `gem_publisher` gem. It will be called by jenkins for each build on master.
> Add rake task to publish gems

- README.md
- Rakefile
- govuk_navigation_helpers.gemspec
- jenkins.sh
- lib/govuk_navigation_helpers.rb
- spec/govuk_navigation_helps_spec.rb
- spec/spec_helper.rb
Implementation is taken from government-frontend, which
doesn't place any restrictions on breadcrumb length.
See https://github.com/alphagov/government-frontend/pull/163
One change in behaviour is this gem always returns a breadcrumb:
if a parent link is not available, it will just show a Home link.
In most cases we want to show a consistent breadcrumb component
on all pages, and we don't know of any cases where we wouldn't
want to root this at the homepage.  If there is any reason not
to show a breacrumb, then the frontend app should avoid calling
this.
> Add breadcrumb helper

- lib/govuk_navigation_helpers.rb
- lib/govuk_navigation_helpers/breadcrumbs.rb
- spec/breadcrumbs_spec.rb
This makes it easier to add a new component without the main class growing too large.
> Move breadcrumbs code into own class

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Since we're going to be using it in production, we need to release version 1.0.0 to indicate we'll follow semantic versioning from now on (semantic versioning doesn't apply < 1).
> Release 1.0.0

- lib/govuk_navigation_helpers/related_items.rb
- spec/related_items_spec.rb
This commit adds the URL of the parent/grandparent to the data returned by the related items helper. The presence of the URL will trigger the related items component to render a “more” link as the last link of the parent/grandparent section.
> Add URL for “more” link to related items helper

- lib/govuk_navigation_helpers/breadcrumbs.rb
- spec/breadcrumbs_spec.rb
This commit changes the breadcrumbs helper to return a hash which can be passed to the `govuk_components` breadcrumbs component. This makes the breadcrumbs helper consistent with the related items helper.
> Make the breadcrumbs helper return a hash

- CHANGELOG.md
- lib/govuk_navigation_helpers.rb
- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/grouped_related_links.rb
- lib/govuk_navigation_helpers/related_items.rb
- spec/related_items_spec.rb
Currently, related items are grouped based on having a common parent or grandparent with the content item they are linked to. This commit changes the grouping logic to group by common `mainstream_browse_pages`, in order to match the currently implemented grouping logic.
> Group related items by mainstream browse page

- lib/govuk_navigation_helpers.rb
- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/taxon_breadcrumbs.rb
- spec/taxon_breadcrumbs_spec.rb
This change adds a navigation helper to get the payload required to render breadcrumbs for taxons. This is called with:
`NavigationHelper.new(content_item).taxon_breadcrumbs`
The code is a direct read-across of the (non-taxon) breadcrumb helper.
Trello: https://trello.com/c/6OIbW5Ad/323-add-functionality-to-govuk-navigation-helpers-to-generate-data-for-the-breadcrumbs-from-the-new-taxonomy
> Add taxon breadcrumb processing

- Jenkinsfile
This moves the Gem onto [Jenkins 2](https://ci.integration.publishing.service.gov.uk/job/govuk_navigation_helpers/).
The Gem publication stage needs to be tested; this will be done in a subsequent Pull Request.
> Migrate to Jenkins 2

- Jenkinsfile
This should add the correct ssh permissions required by the gem publisher to push a tag to Git.
> Add ssh tagging permission to Jenkinsfile

- lib/govuk_navigation_helpers/content_item.rb
- spec/taxon_breadcrumbs_spec.rb
Prior to this change, the format used in the `taxon_breadcrumbs` method was incorrect. That assumed a content item to have the following structure:
```json
{
"links": {
"parent_taxons": []
}
}
```
This skipped out the taxon that the content was actually tagged to, so the format should actually be:
```json
{
"links": {
"taxons": [
{
"links": {
"parent_taxons": []
}
}
]
}
}
```
> Fix taxon breadcrumbs

- .rubocop.yml
For some reason rubocop isn't picking up the ruby version properly on one of
our branches (https://github.com/alphagov/govuk_navigation_helpers/pull/26)
Force it to use the 2.3 parser.
> Add rubocop yaml

- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/taxon_breadcrumbs.rb
- spec/taxon_breadcrumbs_spec.rb
For any pages displaying "taxon" breadcrumbs, we will now display the title of the current page as the final breadcrumb. Clicking on this link will take users to the `#content` anchor on the page.
Dependent on:
Trello: https://trello.com/c/MVM5bueS/386-add-current-page-to-taxonomy-breadcrumbs
> Show current page in breadcrumbs

- lib/govuk_navigation_helpers/content_item.rb
The ContentItem class assumes a number of hash methods that may not
necessarily be available on a content item. By explicitly converting
this object to a hash, we can avoid bad method calls
> Convert content item to hash

- lib/govuk_navigation_helpers.rb
- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/taxon_sidebar.rb
- spec/taxon_sidebar_spec.rb
The new taxonomy navigation requires its content pages to display a
sidebar. The sidebar should contain links to the parent taxons the
content is tagged to.
This commit adds a helper method that accepts a content item payload.
The method uses this payload to generate the appropriate data structure
for the GOVUK sidebar component in static.
https://trello.com/c/0BD3POzu/403-show-parent-taxons-in-the-side-navigation-on-all-education-content-pages
> Add a taxon sidebar method

- lib/govuk_navigation_helpers.rb
- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/taxonomy_sidebar.rb
- spec/taxonomy_sidebar_spec.rb
- Give it a slightly more generic name, given it doesn't just contain
taxons. It may also eventually contain links to content items similar
to the current page, as determined by Rummager.
- Add the taxon description field for use in the sidebar.
For use with the component added here: https://github.com/alphagov/static/pull/905
> Update taxonomy sidebar helper

- lib/govuk_navigation_helpers/content_item.rb
- spec/taxonomy_sidebar_spec.rb
* Back out change to random schema example. Using 'taxon' is
confusing and erroneous as the sidebar is for content pages not taxon
pages.
* Make description field optional as not all parent taxons will have
one.
> Fix taxonomy_sidebar_spec

- lib/govuk_navigation_helpers/taxonomy_sidebar.rb
- spec/taxonomy_sidebar_spec.rb
Govuk Components requires symbol keys.
### Trello 
https://trello.com/c/EJXC60k1/429-add-more-like-this-results-to-side-navigation-in-frontend-apps
> Return related content with symbol keys

- lib/govuk_navigation_helpers/taxonomy_sidebar.rb
- spec/taxonomy_sidebar_spec.rb
The data structure returned by the taxonomy sidebar helper is unnecessarily nested, and the notion of "sections" does not map to our usage (it would always be an array of 1 item, with a title that repeats the current content title).
NB: This is an API-breaking change, so should get a major version bump.
https://trello.com/c/EJXC60k1/429-add-more-like-this-results-to-side-navigation-in-frontend-apps
> Remove sections from taxonomy sidebar response

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Major version change because of the contained breaking change.
https://trello.com/c/EJXC60k1/429-add-more-like-this-results-to-side-navigation-in-frontend-apps
> Bump version to 3.0.0

- lib/govuk_navigation_helpers/taxonomy_sidebar.rb
This has been used in research and should be the default.
> Only show 3 related links on taxonomy sidebar

- CHANGELOG.md
- lib/govuk_navigation_helpers/content_item.rb
- spec/taxon_breadcrumbs_spec.rb
This commit makes sure parent taxons are sorted alphabetically by title
before we select the first one to use. This is for consistency reasons
until we have a way of modelling parent taxons.
Trello: https://trello.com/c/RLWfiG6N/481-make-breadcrumb-use-1st-alphabetic-topic
> Sort parent taxons before selecting the first

- README.md
- lib/govuk_navigation_helpers/configuration.rb
- lib/govuk_navigation_helpers/taxonomy_sidebar.rb
- spec/taxonomy_sidebar_spec.rb
This commit allows the gem to be configured with a statsd client, which
can be used to track counts and timings of the search queries.
When nothing is passed in, a no-op client will be used instead.
Trello: https://trello.com/c/S72dddmO/488-configure-navigation-helpers-with-statsd
> Statsd metric tracking

- lib/govuk_navigation_helpers/guidance.rb
After looking at the `notice` content which has been tagged to taxons, we've decided that it shouldn't appear on taxonomy navigation pages.
Trello: https://trello.com/c/RhEocgyj/42-remove-notices-from-guidance-list
I'm going to make the same change in [govuk_document_types|github.com/alphagov/govuk_document_types].
> Remove `notice` from guidance document types

- lib/govuk_navigation_helpers/taxon_breadcrumbs.rb
- spec/taxon_breadcrumbs_spec.rb
This will allow the breadcrumb component in static to collapse the breadcrumbs to just the parent taxon in the mobile view.
https://trello.com/c/Y7OirowB/472-mobile-version-of-breadcrumbs-should-only-show-previous-link
The new flag is used in alphagov/static#948, but they can be merged in any order.
> Identify parent taxon in breadcrumb helper

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
https://trello.com/c/Y7OirowB/472-mobile-version-of-breadcrumbs-should-only-show-previous-link
> Release version 3.2.1

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
I've bumped the major version number because this is technically a breaking change (removing `Guidance::DOCUMENT_TYPES`. Is that the right thing to do in this library?
> Release version 4.0.0

- lib/govuk_navigation_helpers/taxonomy_sidebar.rb
- spec/taxonomy_sidebar_spec.rb
This is not a new feature. It used to be done in [static](https://github.com/alphagov/static/blob/master/app/views/govuk_component/taxonomy_sidebar.raw.html.erb#L31). That is problematic for a number of reasons:
- we might be making calls to the search API that won't get used in the
frontend apps. An example of this is when a piece of content is tagged
to more than 2 taxons. We would be making an API call for each of the
taxons, but only displaying the results of the first 2;
- we will want to display curated related links underneath the taxonomy
links. Again, if a content item is tagged to more than 2 taxons, we
wouldn't be displaying links for sections such as "Elsewhere on
GOV.UK".
After this change is live, we can remove the equivalent functionality in
static.
Trello: …
> Limit related links to first 2 taxons in sidebar

- govuk_navigation_helpers.gemspec
Use the latest version of gds-api-adapters, which has had a major version number increase.
The new version renames the `GOVUK_FACT_CHECK_ID` header to `GOVUK_AUTH_BYPASS_ID` in the middleware.
Trello: https://trello.com/c/u1H1rgDA/525-some-finding-pages-are-still-being-tracked-as-thing
This will let us bump the gds-api-adapters version number on projects which depend on both that project and govuk_navigation_helpers.
> Update the gds-api-adapters gem

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Increase the major version number because the gds-api-adapters gem update changes the headers added by the Rails middleware which will affect how content store changes are linked to admin users. This means that upgrading to this version should not be done silently with a minor version increase.
https://trello.com/c/u1H1rgDA/525-some-finding-pages-are-still-being-tracked-as-thing
> Release version 5.0.0

- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/taxonomy_sidebar.rb
- spec/taxonomy_sidebar_spec.rb
This commit adds both curated and external related links to the taxonomy
sidebar. This will allow us to show the new taxonomy sidebar for some
mainstream content where we manually show the old related links.
This commit will allow us to revert
https://github.com/alphagov/frontend/commit/02b6ad2b2825c61daeca469836e6917f3b9032fd
Here is an example page with all 3 sections: https://www.gov.uk/api/content/student-finance
And it will look like this:
Trello: https://trello.com/c/vM6Kaw9B/546-ias-and-content-designers-can-curate-related-links-for-any-content-type
> Include curated and external links in sidebar

- CHANGELOG.md
- govuk_navigation_helpers.gemspec
The new version of the gem gds-api-adapters now makes lgil mandatory when requesting links from Local Links Manager, so Frontend needs to be using that version (42.0.0). 
In order to do that, we need to upgrade govuk_navigation_helpers from depending on gds-api-adapters 41.0 to 42.0.
https://trello.com/c/jk9mNWop/46-upgrade-frontend-to-gds-api-adapters-42-0-0
> Upgrade gds-api-adapters to 42.0

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Upgrades gds-api-adapters to 42.2.0, which contains breaking changes
(https://github.com/alphagov/gds-api-adapters/blob/master/CHANGELOG.md#4200),
hence the major bump.
> Bump to 6.0.0

- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/taxonomy_sidebar.rb
- spec/taxonomy_sidebar_spec.rb
In this PR, we:
- delete the curated related links and external related links from the new taxonomy, as there is still no consensus if this should be shown;
- remove duplicated related links across different taxons on the same page.
As an example, the following page has repeated links in between different taxons on the side navigation:
https://www.gov.uk/government/publications/national-curriculum-in-england-art-and-design-programmes-of-study
With this change, we prevent duplication and it will look like this (example from the navigation prototype using this change):
https://govuk-nav-prototype-pr-11.herokuapp.com/government/publications/national-curriculum-in-england-art-and-design-programmes-of-study
As you can see, there is no repetition of related links between the sidebar taxons. …
> Remove duplicated related links

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Bug fix related to duplicate related links.
Trello: https://trello.com/c/I4rs80n1/80-remove-duplicated-related-links-across-all-parent-taxons
> Release version 6.0.1

- CHANGELOG.md
Missed in [previous PR](https://github.com/alphagov/govuk_navigation_helpers/pull/74)
> Update Changelog with previous changes

- govuk_navigation_helpers.gemspec
- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/related_items.rb
- spec/related_items_spec.rb
For completed transactions with the "register_to_vote" promotion, we
should display the new section in the related links in order to
encourage people to register to vote.
Trello: https://trello.com/c/QbnidEBA/97-add-promotion-for-register-to-vote-to-transaction-done-pages
Waiting on product feedback before this should be merged.
> Add "Register to Vote" section to related links

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Updated CHANGELOG to reflect what has changed.
Trello: https://trello.com/c/Bu5TJMaG/104-remove-code-related-to-register-to-vote
> Release a new version of govuk_navigation_helper

- lib/govuk_navigation_helpers.rb
- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/curated_taxonomy_sidebar_links.rb
- lib/govuk_navigation_helpers/rummager_taxonomy_sidebar_links.rb
- lib/govuk_navigation_helpers/taxonomy_sidebar.rb
- spec/taxonomy_sidebar_spec.rb
When a content item has related link overrides for the new education
(configured in `content-tagger`), then `govuk_navigation_helpers` will
present a hash that contains these curated links, rather than the
Elasticsearch “More like this” links generated by `rummager`.
Curated links are grouped according to the following rules:
- If a related item has a taxon in common with the content, then display
the related item under that taxon in the sidebar (avoiding duplicates)
- Otherwise display a related item under the “Elsewhere on GOV.UK”
section
- Any external related links are displayed under “Elsewhere on the web”.
External related links currently use the same external links as the
“old” related items sidebar. In order to prevent sidebar overrides
for content items with external related …
> Present curated taxonomy sidebar links

- spec/taxon_breadcrumbs_spec.rb
This test was failing on master. It seems to be looking for the
'guidance' schema which doesn't exist (anymore?). Instead we update
the spec to use the 'answer' document type.
In the `breadcrumbs_for` method we should be fetching an example
for the given content item's document type, not 'taxon' as was
previously the case (which was another reason for failing the spec).
Update the context wording around 'taxon with taxon parents' and
'taxon content item with taxon parents’ as I believe those two were
the wrong way around.
We also update the spec to use 2 space indentation.
> Fix failing taxon breadcrumb spec

- lib/govuk_navigation_helpers/content_item.rb
- spec/content_item_spec.rb
- spec/taxon_breadcrumbs_spec.rb
- spec/taxonomy_sidebar_spec.rb
For https://trello.com/c/b3TTdin2/157-prevent-publishers-seeing-draft-taxons-in-government-frontend
Since we’ve created the new single taxonomy in draft in Production, some publishers have been seeing some of those draft taxons in the sidebar and breadcrumbs when previewing their content on the draft stack.
In order to avoid this, we add a hardcoded whitelist of taxons which we want to show (including all their sub taxons), both in draft and production. This whitelist corresponds to the current published branches World, Education and Parenting. We currently don’t expect to be publishing any new taxonomy branches, so we think that this approach will work for the time being. We expect to remove this whitelist when the single taxonomy is more settled and/or is published.
> Whitelist root taxons

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Root taxons are now whitelisted, so that only taxons descendant from one of
the three published root taxons (education, childcare-parenting and world)
will appear in breadcrumbs and the side bar. See the [PR](https://github.com/alphagov/govuk_navigation_helpers/pull/82) for more information
> Update to version 7.0

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Add helper which provides data for related navigation sidebar which will be used on content pages with unvirsal layout. Logic is in addition to existing related items and taxonomy sidebar, so not a breaking change.
> Update version 7.1.0

- lib/govuk_navigation_helpers.rb
The related navigation component was originally called 'related navigation sidebar'. It has been renamed since, making the link to the component in heroku incorrect.
> Update link to related navigation component

- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/related_navigation_sidebar.rb
- spec/navigation_sidebar_spec.rb
We want to show world location data alongside organisations in the related navigation component. 
This will live in its own section in the related navigation component, e.g:
The title for this section is still WIP, but this change will be made in `government-frontend` as part of https://github.com/alphagov/government-frontend/pull/565
> Return world location data for related navigation

- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/related_navigation_sidebar.rb
- spec/navigation_sidebar_spec.rb
- spec/related_navigation_sidebar_spec.rb
https://trello.com/c/iWa3b1Gd/164-navigation-sidebar-is-not-showing-topical-events
Navigation sidebar should also show Topical Events.
> Add topical events to related navigation

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
https://trello.com/c/iWa3b1Gd/164-navigation-sidebar-is-not-showing-topical-events
Adds topical events and worldwide orgs to related navigatio sidebar helper.
> Bump version to 7.3.0

- config/tasklists/end-a-civil-partnership.json
- config/tasklists/get-a-divorce.json
- config/tasklists/learn-to-drive-a-car.json
- govuk_navigation_helpers.gemspec
- lib/govuk_navigation_helpers.rb
- lib/govuk_navigation_helpers/current_tasklist_ab_test.rb
- lib/govuk_navigation_helpers/tasklist_content.rb
- spec/tasklist_content_spec.rb
We moved the Tasklist functionality into GovukNavigationHelpers
so we can consolidate the code in one place.
It no longer uses `concerns` and instead the functionality is split in
two objects:
- TasklistContent: receives the current request.path and tries to find a
tasklist that has that path, in case of one being used between "End
Civil Partnership" and "Get Divorce", "Get Divorce" tasklist is the
default.
- CurrentTasklistAbTest: Depends on having a current tasklist set to
enable the AbTest and set it on the response headers.
- Added JSON files for "Learn to Drive a car", "Get Divorce" & "End a
Civil Partnership", this are the structure necessary to render the
TasklistSidebar and TasklistHeader
This commit brings the TasklistContent functionality into a single place,
we have also added …
> Add TasklistContent & CurrentTasklistAbTest

- lib/govuk_navigation_helpers/current_tasklist_ab_test.rb
- spec/current_tasklist_ab_test_spec.rb
We want to display headers if the page is in the AB test whether or not the
sidebar is shown.
Also, we only want to show the sidebar if the page is in the test cohort.
Also, added some rudimentary tests to make sure we're calling the ab test component when we're supposed to.
> Tweak tasklist AB logic

- lib/govuk_navigation_helpers/current_tasklist_ab_test.rb
Publications now use a template which has a sidebar, so we don't need to include any special cases for this.
> Remove publications special case

- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/related_navigation_sidebar.rb
- spec/related_navigation_sidebar_spec.rb
https://govuk.zendesk.com/agent/tickets/2538570
Include statistical data sets in related navigation helper.
> Add statistical data sets to related navigation helper

- lib/govuk_navigation_helpers/related_navigation_sidebar.rb
- spec/related_navigation_sidebar_spec.rb
https://trello.com/c/1nhkSnqd/180-navigating-to-a-world-location-page-is-broken-from-the-sidebar
https://govuk.zendesk.com/agent/tickets/2539244
World location titles may contain non-alphanumeric characters
eg. `UK Mission to the United Nations, New York`
which need to be stripped while building the location slug for the location base path.
I've based the parameterize method on the [Rails implementation](https://apidock.com/rails/ActiveSupport/Inflector/parameterize) though
the i18n `transliterate` method isn't included as I don't believe it's necessary.
> Parameterise world location links

- lib/govuk_navigation_helpers/related_navigation_sidebar.rb
- spec/related_navigation_sidebar_spec.rb
While moving over answer and help pages to the universal layout, we [noticed](https://github.com/alphagov/government-frontend/pull/649#issuecomment-354800476) that mainstream topics were not being displayed in the related navigation sidebar. We need to include this data in the data that is returned for the sidebar.
> Return mainstream topics to related nav

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Update related navigation sidebar helper to return mainstream topics alongside whitehall topics
> Bump version to 8.2.0

- lib/govuk_navigation_helpers/related_navigation_sidebar.rb
- spec/related_navigation_sidebar_spec.rb
https://trello.com/c/3bBRadW4/229-create-a-rule-to-remove-mainstream-browse-whitehall-topic-sidebar-duplication
We add mainstream browse page links to related topics where relevant.
There are occasions where the mainstream link text will be identical to the existing topic text.
In this case we prefer the mainstream browse link over the existing topic.
> De-duplicate topics links

- spec/related_navigation_sidebar_spec.rb
Merging https://github.com/alphagov/govuk_navigation_helpers/pull/110 resulting in the [master branch build failing](https://ci.integration.publishing.service.gov.uk/job/govuk_navigation_helpers/job/master/) despite the PR branch being clean. This flaky test seems to be the culprit.
> Fix flaky test, it's failing in master branch.

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
- Update related navigation sidebar helper to de-duplicate mainstream topics with the same title as Whitehall topics. Mainstream topics are preferred in the case of duplicates.
> Bump version to 8.2.1

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
https://trello.com/c/cxPboFUb/285-update-sidebar-breadcrumbs-components-to-only-show-taxons-with-the-live-phase-this-replaces-the-current-whitelisting-taxon-metho 
* Check if a taxon's phase is 'live' to determine if it should be passed to a navigation component to be displayed on a page.
* Remove the old content_id whitelisting approach to filtering for taxons.
> Bump version to 9.1.0

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
For https://trello.com/c/nGtzTPCu/283-update-government-frontend-to-use-relatednavigation-component
> Bump to 9.2.0

- CHANGELOG.md
- lib/govuk_navigation_helpers/taxon_breadcrumbs.rb
- spec/taxon_breadcrumbs_spec.rb
For https://trello.com/c/RCjHKJb8/125-only-show-the-parent-taxons-in-the-breadcrumbs
We don't want to show the current topic page title in taxon breadcrumbs, as
currently there is duplication between the breadcrumbs and the page header
title on pages that use taxon breadcrumbs.
**Before**
**After**
**Before**
**After**
> Return only parent taxons in taxon breadcrumbs
