- Rakefile
- govuk_navigation_helpers.gemspec
- jenkins.sh
- lib/govuk_navigation_helpers/version.rb
This PR adds govuk-lint, fixes existing problems and sets up CI.
> Add linting

- README.md
This commit amends the usage docs to reflect the changes to the breadcrumbs helper, and adds usage docs for the related items helper.
> Fix usage documentation

- lib/govuk_navigation_helpers/breadcrumbs.rb
More details in the commit messages.
> Refactor breadcrumbs class

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Bump the version to try and trigger a Jenkins 2 build and Gem publication.
> Bump version to 2.1.1

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Bump version to 2.1.2. This should hopefully fix the Gem publishing pipeline.
> Bump version to 2.1.2

- spec/taxon_breadcrumbs_spec.rb
At the moment, we can generate breadcrumbs for both:
- a taxon, by using the `parent_taxons` link type;
- another content item, by using the `taxons` link type.
This commit makes this distinction in the breadcrumb tests so the
behaviour is clearer.
> Refactor breadcrumb tests to be explicit about API

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Add support for current page in taxon breadcrumbs.
> Bump version to 2.3.0

- Jenkinsfile
This moves the logic for Gem publishing away from the [Gem Publisher](https://github.com/alphagov/gem_publisher) gem, and into the `Jenkinsfile`, where it is executed as part of the build chain instead.
The motivation for this change is that getting Gem Publisher to work with the new Jenkins 2 CI environment has been non-trivial (and remains unsolved on eg [API Adapters](https://github.com/alphagov/gds-api-adapters)).
If this is a successful and accepted approach, this could be extracted into Puppet's [`govuk_jenkinslib.groovy`](https://github.com/alphagov/govuk-puppet/blob/master/modules/govuk_jenkins/files/var/lib/jenkins/groovy_scripts/govuk_jenkinslib.groovy) file for use across projects.
> Publish Gem from Jenkins

- Jenkinsfile
Uses the commonised gem publishing function in Puppet.
> Use commonised Gem publishing function

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Trello: https://trello.com/c/EJXC60k1/429-add-more-like-this-results-to-side-navigation-in-frontend-apps
> Bump version to 2.4.1

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
This isn't technically a bug fix, but it isn't new functionality either.
I think a PATCH version change is enough.
> Upgrade gem to 3.0.1

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Trello: https://trello.com/c/yTDsFUrm/468-style-changes-to-taxon-grid-pages-in-collections
> Release version 3.0.2

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
> Release version 3.1.0

- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/taxonomy_sidebar.rb
- spec/taxonomy_sidebar_spec.rb
https://trello.com/c/RJeCjY7c/510-add-sorting-of-taxons-and-related-links-to-nav-helpers-gem
> Add sorting of taxons and related links in taxonomy sidebar

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Trello: https://trello.com/c/vM6Kaw9B/546-ias-and-content-designers-can-curate-related-links-for-any-content-type
> Release version 5.1.0

- CHANGELOG.md
Added a link to make it easier to navigate to the correct place.
> Make it easier to see the change on gds-api-adapters

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Trello: https://trello.com/c/QbnidEBA/97-add-promotion-for-register-to-vote-to-transaction-done-pages
> Release version 6.1.0

- govuk_navigation_helpers.gemspec
- lib/govuk_navigation_helpers/content_item.rb
- lib/govuk_navigation_helpers/related_items.rb
- spec/related_items_spec.rb
Trello: https://trello.com/c/Bu5TJMaG/104-remove-code-related-to-register-to-vote
> Remove register to vote from related links

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Trello: https://trello.com/c/J8ofEnrt/167-display-curated-related-links-in-the-sidebar
> Release version 6.3.0

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Update related navigation sidebar helper to also return world location data
> Update to 7.2.0

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Change content for the Get Divorce & End Civil Partnership tasklists
> Bump version to 7.5.1

- config/tasklists/end-a-civil-partnership.json
The link was going to divorce content in error.
> Update link in end-a-civil-partnership content

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
We've removed the special handling of tasklists on publications and fixed
some content.
> Bump major version

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
Related to https://govuk.zendesk.com/agent/tickets/2538570
> Bump version to 8.1.0

- config/tasklists/end-a-civil-partnership.json
- config/tasklists/get-a-divorce.json
- config/tasklists/learn-to-drive-a-car.json
- spec/tasklist_content_spec.rb
The Modelling Services team have some content updates to make to the `Learn to drive a car`, `End a civil partnership` and `Get a divorce` tasklists.
> Update to tasklists

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
There have been some updates to the /end-a-civil-partnership, /get-a-divorce, and /learn-to-drive-a-car tasklists.
> Bump version to 8.1.1

- config/tasklists/end-a-civil-partnership.json
- config/tasklists/get-a-divorce.json
Changes to the content of Get a divorce and End a civil partnership task lists.
Should be the same changes as in https://github.com/alphagov/collections/pull/459
Trello card: https://trello.com/c/ff5eF2XK/416-update-task-list-content
> Update task list content

- govuk_navigation_helpers.gemspec
Security vulnerability reported in the current version.
> Update Yard to 0.9.12

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
> Bump patch version

- CHANGELOG.md
- lib/govuk_navigation_helpers/version.rb
We've removed AB testing bits from task lists, renamed things and changed a
schema.
> Bump to major version
